<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD:王函瑜/XueliProject/test-output/junitreports/TEST-com.edu.test.OverWork_Check_Test.xml
<testsuite hostname="LAPTOP-OHIPPB3J" failures="0" tests="1" name="com.edu.test.OverWork_Check_Test" time="8.787" errors="0" timestamp="07 12月 2018 00:32:40 GMT" skipped="0">
  <testcase classname="com.edu.test.OverWork_Check_Test" name="look_work" time="8.787"/>
</testsuite> <!-- com.edu.test.OverWork_Check_Test -->
=======
<testsuite hostname="PC" failures="0" tests="3" name="com.edu.test.TestA" time="48.868" errors="1" timestamp="11 12月 2018 09:08:17 GMT" skipped="0">
  <testcase classname="com.edu.test.TestA" name="loginfail" time="22.194">
    <error message="Must provide a location for a move action." type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Must provide a location for a move action.
at org.openqa.selenium.interactions.MoveMouseAction.<init>(MoveMouseAction.java:38)
at org.openqa.selenium.interactions.Actions.moveToElement(Actions.java:388)
at com.edu.core.WebDriverEngine.mouseoverElement(WebDriverEngine.java:276)
at com.edu.test.TestA.loginfail(TestA.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </error>
  </testcase> <!-- loginfail -->
  <testcase classname="com.edu.test.TestA" name="before_Login2" time="16.636"/>
  <testcase classname="com.edu.test.TestA" name="before_Login" time="10.038"/>
</testsuite> <!-- com.edu.test.TestA -->
>>>>>>> 1191a5a979de8933a40535de839db9e33a7af004:王函瑜/XueliProject2/test-output/junitreports/TEST-com.edu.test.TestA.xml
