<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="且说"
           tests="8"
           failures="1"
           errors="0"
           skipped="0"
           time="199.711">
  <properties />
            <testcase name="comment2" time="19.278" classname="com.edu.test.QieShuo_Test">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertTrue(Assert.java:44)
  org.testng.Assert.assertTrue(Assert.java:54)
  com.edu.test.QieShuo_Test.comment2(Unknown Source)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.TestNG.privateMain(TestNG.java:1354)
  org.testng.TestNG.main(TestNG.java:1323)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="commentCode" time="29.527" classname="com.edu.test.QieShuo_Test" />
                <testcase name="commentLong_Fail3" time="22.836" classname="com.edu.test.QieShuo_Test" />
                <testcase name="commentLong_Fail2" time="23.140" classname="com.edu.test.QieShuo_Test" />
                <testcase name="commentLong" time="32.144" classname="com.edu.test.QieShuo_Test" />
                <testcase name="comment" time="20.365" classname="com.edu.test.QieShuo_Test" />
                <testcase name="commentLong_Fail1" time="29.630" classname="com.edu.test.QieShuo_Test" />
                <testcase name="commentPic" time="22.791" classname="com.edu.test.QieShuo_Test" />
      
</testsuite>
